"""yarn.lock (yarn 1 / Classic) loader + rule reuse tests.

Exercises both layers:

1. ``_parse_yarn_lock`` + ``_synthesize_yarn_lock`` unit tests:
   single- and multi-pattern headers, scoped names, comments,
   blank lines, sub-blocks (``dependencies:`` skipped), multi-
   version installs.
2. End-to-end via ``NpmContext.from_path``: a real ``yarn.lock``
   on disk produces an :class:`NpmLock` that :class:`NpmChecks`
   fans out across NPM-002 / NPM-003 / NPM-006 without per-rule
   changes.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from pipeline_check.core.checks.npm.base import (
    NpmContext,
    _parse_yarn_lock,
    _split_yarn_pattern,
    _synthesize_yarn_lock,
)
from pipeline_check.core.checks.npm.pipelines import NpmChecks

# ── _split_yarn_pattern ─────────────────────────────────────────────


class TestSplitYarnPattern:
    def test_bare_name_at_caret_range(self) -> None:
        assert _split_yarn_pattern("lodash@^4.17.21") == "lodash"

    def test_quoted_pattern(self) -> None:
        assert _split_yarn_pattern('"lodash@^4.17.21"') == "lodash"

    def test_scoped_name_quoted(self) -> None:
        assert _split_yarn_pattern('"@babel/code-frame@^7.0.0"') == (
            "@babel/code-frame"
        )

    def test_npm_protocol_berry_shape(self) -> None:
        # Defensive: berry-shaped pattern slipping past the
        # dispatcher should still surface the package name cleanly.
        assert _split_yarn_pattern('"lodash@npm:^4.17.21"') == "lodash"

    def test_empty_returns_none(self) -> None:
        assert _split_yarn_pattern("") is None

    def test_bare_name_no_range_passes_through(self) -> None:
        # Defensive: never seen in real yarn.lock, but tolerated.
        assert _split_yarn_pattern("lodash") == "lodash"


# ── _parse_yarn_lock ────────────────────────────────────────────────


class TestParseYarnLock:
    def test_single_entry(self) -> None:
        body = textwrap.dedent(
            """\
            # THIS IS AN AUTOGENERATED FILE.
            # yarn lockfile v1

            lodash@^4.17.21:
              version "4.17.21"
              resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"
              integrity sha512-aaa==
            """
        )
        out = _parse_yarn_lock(body)
        assert len(out) == 1
        patterns, props = out[0]
        assert patterns == ["lodash@^4.17.21"]
        assert props["version"] == "4.17.21"
        assert props["resolved"].startswith("https://registry.yarnpkg.com/")
        assert props["integrity"] == "sha512-aaa=="

    def test_multi_pattern_header(self) -> None:
        # The common yarn 1 shape: two specifier patterns resolve
        # to the same install, both listed in the header.
        body = textwrap.dedent(
            """\
            "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.16.0":
              version "7.16.7"
              resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.16.7.tgz#x"
              integrity sha512-bbb==
            """
        )
        out = _parse_yarn_lock(body)
        assert len(out) == 1
        patterns, _ = out[0]
        assert patterns == [
            '"@babel/code-frame@^7.0.0"', '"@babel/code-frame@^7.16.0"',
        ]

    def test_sub_blocks_skipped(self) -> None:
        # Yarn 1 emits a nested ``dependencies:`` block below the
        # primary properties; the parser must skip it without
        # recording transitive metadata as primary properties.
        body = textwrap.dedent(
            """\
            foo@^1.0.0:
              version "1.0.0"
              resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz#y"
              integrity sha512-ccc==
              dependencies:
                bar "^2.0.0"
                baz "^3.0.0"

            bar@^2.0.0:
              version "2.0.0"
              resolved "https://registry.yarnpkg.com/bar/-/bar-2.0.0.tgz#z"
              integrity sha512-ddd==
            """
        )
        out = _parse_yarn_lock(body)
        assert len(out) == 2
        # The first entry's props should NOT carry ``bar`` /
        # ``baz`` — those live inside the sub-block.
        _, props = out[0]
        assert "bar" not in props and "baz" not in props
        assert props["version"] == "1.0.0"

    def test_comments_and_blank_lines_tolerated(self) -> None:
        body = textwrap.dedent(
            """\
            # comment


            lodash@^4.0.0:
              # inline comment line above a property is rare but valid
              version "4.17.21"
              resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"
              integrity sha512-aaa==

            """
        )
        out = _parse_yarn_lock(body)
        assert len(out) == 1
        assert out[0][1]["version"] == "4.17.21"


# ── _synthesize_yarn_lock ───────────────────────────────────────────


class TestSynthesizeYarnLock:
    def test_basic_record_shape(self) -> None:
        entries = [
            (
                ["lodash@^4.17.21"],
                {
                    "version": "4.17.21",
                    "resolved": (
                        "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
                    ),
                    "integrity": "sha512-aaa==",
                },
            ),
        ]
        out = _synthesize_yarn_lock(entries)
        rec = out["packages"]["node_modules/lodash"]
        assert rec["name"] == "lodash"
        assert rec["version"] == "4.17.21"
        assert rec["integrity"] == "sha512-aaa=="
        assert rec["resolved"].endswith("/lodash-4.17.21.tgz")

    def test_scoped_install_path(self) -> None:
        entries = [
            (
                ['"@babel/code-frame@^7.0.0"'],
                {
                    "version": "7.16.7",
                    "resolved": "https://registry.yarnpkg.com/.../x.tgz",
                    "integrity": "sha512-bbb==",
                },
            ),
        ]
        out = _synthesize_yarn_lock(entries)
        assert "node_modules/@babel/code-frame" in out["packages"]

    def test_multi_version_disambiguation(self) -> None:
        entries = [
            (
                ["foo@^1.0.0"],
                {"version": "1.0.0", "resolved": "x", "integrity": "sha512-1=="},
            ),
            (
                ["foo@^2.0.0"],
                {"version": "2.0.0", "resolved": "x", "integrity": "sha512-2=="},
            ),
        ]
        out = _synthesize_yarn_lock(entries)
        # Second version lands under a disambiguated install path
        # so both records reach the rule layer.
        assert out["packages"]["node_modules/foo"]["version"] == "1.0.0"
        assert (
            out["packages"]["node_modules/foo+2.0.0"]["version"] == "2.0.0"
        )

    def test_missing_resolved_record_still_emitted(self) -> None:
        entries = [
            (
                ["foo@1.0.0"],
                {"version": "1.0.0", "integrity": "sha512-eee=="},
            ),
        ]
        out = _synthesize_yarn_lock(entries)
        rec = out["packages"]["node_modules/foo"]
        assert rec["name"] == "foo"
        assert "resolved" not in rec
        # NPM-002 will skip this (no resolved); the record's
        # presence still lets NPM-006 see the (name, version)
        # tuple.


# ── Integration: end-to-end via NpmContext.from_path ─────────────


_YARN_LOCK_BODY = textwrap.dedent(
    """\
    # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    # yarn lockfile v1

    lodash@^4.17.21:
      version "4.17.21"
      resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
      integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==

    ua-parser-js@0.7.29:
      version "0.7.29"
      resolved "https://registry.yarnpkg.com/ua-parser-js/-/ua-parser-js-0.7.29.tgz#fff"
      integrity sha512-malicious=
    """
)


def _write_yarn_lock(tmp_path: Path) -> Path:
    target = tmp_path / "yarn.lock"
    target.write_text(_YARN_LOCK_BODY, encoding="utf-8")
    return target


def test_yarn_lock_picked_up_by_loader(tmp_path: Path) -> None:
    _write_yarn_lock(tmp_path)
    ctx = NpmContext.from_path(tmp_path)
    assert len(ctx.locks) == 1
    lock = ctx.locks[0]
    assert lock.lockfile_version == 3
    pkgs = lock.data["packages"]
    assert "node_modules/lodash" in pkgs
    assert "node_modules/ua-parser-js" in pkgs


def test_yarn_lock_npm002_clean_with_integrity(tmp_path: Path) -> None:
    _write_yarn_lock(tmp_path)
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm002 = [f for f in findings if f.check_id == "NPM-002"]
    assert npm002 and all(f.passed for f in npm002)


def test_yarn_lock_npm003_clean_for_registry_source(tmp_path: Path) -> None:
    _write_yarn_lock(tmp_path)
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm003 = [f for f in findings if f.check_id == "NPM-003"]
    assert npm003 and all(f.passed for f in npm003)


def test_yarn_lock_npm003_fires_on_git_ssh_resolved(tmp_path: Path) -> None:
    body = textwrap.dedent(
        """\
        # yarn lockfile v1

        forked@git+ssh://git@host/o/r.git:
          version "1.0.0"
          resolved "git+ssh://git@host/o/r.git#deadbeef"
        """
    )
    (tmp_path / "yarn.lock").write_text(body, encoding="utf-8")
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm003 = [f for f in findings if f.check_id == "NPM-003"]
    assert npm003 and not npm003[0].passed
    assert "ssh" in npm003[0].description.lower()


def test_yarn_lock_npm006_flags_compromised_version(tmp_path: Path) -> None:
    _write_yarn_lock(tmp_path)  # body pins ua-parser-js@0.7.29
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm006 = [f for f in findings if f.check_id == "NPM-006"]
    assert npm006 and not npm006[0].passed
    assert "ua-parser-js" in npm006[0].description
