"""Yarn 2+ / Berry lockfile loader + rule reuse tests.

Mirrors :mod:`tests.npm.test_yarn_lock` for the Berry format. Berry's
header (``__metadata:``), value names (``resolution`` / ``checksum``),
and protocol-embedded patterns (``name@npm:^1.2.3``) all differ from
yarn-1; this module locks the detector, the parser, the synthesizer,
and end-to-end NPM-002 / NPM-003 / NPM-006 reuse against a real Berry
body.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from pipeline_check.core.checks.npm.base import (
    NpmContext,
    _classify_berry_resolution,
    _is_yarn_berry,
    _parse_yarn_berry_lock,
    _split_berry_pattern,
    _synthesize_yarn_berry_lock,
)
from pipeline_check.core.checks.npm.pipelines import NpmChecks

# ── _is_yarn_berry ──────────────────────────────────────────────────


class TestIsYarnBerry:
    def test_classic_yarn1_header_false(self) -> None:
        body = textwrap.dedent(
            """\
            # THIS IS AN AUTOGENERATED FILE.
            # yarn lockfile v1

            lodash@^4.17.21:
              version "4.17.21"
            """
        )
        assert _is_yarn_berry(body) is False

    def test_berry_metadata_header_true(self) -> None:
        body = textwrap.dedent(
            """\
            # This file is generated by running "yarn install".
            # Manual changes might be lost.

            __metadata:
              version: 6
              cacheKey: 8

            "lodash@npm:^4.17.21":
              version: 4.17.21
              resolution: "lodash@npm:4.17.21"
              checksum: ee
              languageName: node
              linkType: hard
            """
        )
        assert _is_yarn_berry(body) is True


# ── _split_berry_pattern ────────────────────────────────────────────


class TestSplitBerryPattern:
    def test_npm_protocol_simple(self) -> None:
        assert _split_berry_pattern("lodash@npm:^4.17.21") == "lodash"

    def test_npm_protocol_quoted(self) -> None:
        assert _split_berry_pattern('"lodash@npm:^4.17.21"') == "lodash"

    def test_scoped_package(self) -> None:
        assert _split_berry_pattern('"@babel/code-frame@npm:^7.0.0"') == (
            "@babel/code-frame"
        )

    def test_workspace_pattern(self) -> None:
        assert _split_berry_pattern(
            "myrepo@workspace:packages/myrepo"
        ) == "myrepo"

    def test_patch_pattern(self) -> None:
        assert _split_berry_pattern(
            '"lodash@patch:lodash@npm:^4.17.21#./patches/x.patch"'
        ) == "lodash"

    def test_empty_returns_none(self) -> None:
        assert _split_berry_pattern("") is None


# ── _classify_berry_resolution ──────────────────────────────────────


class TestClassifyBerryResolution:
    def test_npm_protocol_yields_registry_url(self) -> None:
        protocol, resolved = _classify_berry_resolution(
            "lodash@npm:4.17.21"
        )
        assert protocol == "npm"
        assert resolved.startswith("https://registry.yarnpkg.com/lodash/")
        assert resolved.endswith("lodash-4.17.21.tgz")

    def test_scoped_npm_uses_unscoped_filename(self) -> None:
        # Real yarn synthesized path is /@babel/code-frame/-/code-frame-X.tgz
        protocol, resolved = _classify_berry_resolution(
            "@babel/code-frame@npm:7.18.6"
        )
        assert protocol == "npm"
        assert "@babel/code-frame" in resolved
        assert resolved.endswith("code-frame-7.18.6.tgz")

    def test_workspace_protocol_yields_file_local(self) -> None:
        protocol, resolved = _classify_berry_resolution(
            "myrepo@workspace:packages/myrepo"
        )
        assert protocol == "workspace"
        assert resolved.startswith("file:")

    def test_patch_unwraps_to_underlying_npm(self) -> None:
        protocol, resolved = _classify_berry_resolution(
            "lodash@patch:lodash@npm:4.17.21#./x.patch::version=1"
        )
        assert protocol == "npm"
        assert resolved.startswith("https://registry.yarnpkg.com/")

    def test_git_protocol_yields_git_ssh_resolved(self) -> None:
        protocol, resolved = _classify_berry_resolution(
            "forked@git:host:o/r.git#abc"
        )
        assert protocol == "git"
        assert resolved.startswith("git+ssh://")


# ── _parse_yarn_berry_lock + _synthesize_yarn_berry_lock ────────────


_BERRY_BODY = textwrap.dedent(
    """\
    # This file is generated by running "yarn install" inside your project.

    __metadata:
      version: 6
      cacheKey: 8

    "lodash@npm:^4.17.21":
      version: 4.17.21
      resolution: "lodash@npm:4.17.21"
      checksum: eb835a2e51d381e561e508ce932ea50a8e5a68f4ebdd771ea240d3048244a8d13658acbd502cd4829768c56f2e16bdd4340b9ea141297d472517b83868e677f7
      languageName: node
      linkType: hard

    "ua-parser-js@npm:0.7.29":
      version: 0.7.29
      resolution: "ua-parser-js@npm:0.7.29"
      checksum: bad
      languageName: node
      linkType: hard

    "myrepo@workspace:.":
      version: 0.0.0-use.local
      resolution: "myrepo@workspace:."
      languageName: unknown
      linkType: soft
    """
)


class TestParseAndSynthesizeBerry:
    def test_parse_yields_three_real_entries(self) -> None:
        entries = _parse_yarn_berry_lock(_BERRY_BODY)
        # Includes __metadata; synthesizer drops it. Parser keeps it.
        names = [pats[0] for pats, _ in entries]
        assert any(p == "__metadata" for p in names)
        assert any('lodash@npm:^4.17.21' in p for p in names)

    def test_synthesize_drops_metadata_keeps_real_entries(self) -> None:
        entries = _parse_yarn_berry_lock(_BERRY_BODY)
        out = _synthesize_yarn_berry_lock(entries)
        pkgs = out["packages"]
        assert "node_modules/__metadata" not in pkgs
        assert "node_modules/lodash" in pkgs
        assert "node_modules/ua-parser-js" in pkgs

    def test_npm_protocol_record_has_registry_resolved(self) -> None:
        entries = _parse_yarn_berry_lock(_BERRY_BODY)
        out = _synthesize_yarn_berry_lock(entries)
        record = out["packages"]["node_modules/lodash"]
        assert record["resolved"].startswith(
            "https://registry.yarnpkg.com/"
        )
        assert record["integrity"].startswith("sha512-")

    def test_workspace_record_carries_link_true(self) -> None:
        entries = _parse_yarn_berry_lock(_BERRY_BODY)
        out = _synthesize_yarn_berry_lock(entries)
        record = out["packages"]["node_modules/myrepo"]
        assert record.get("link") is True


# ── End-to-end via NpmContext.from_path ─────────────────────────────


def _write_berry_lock(tmp_path: Path) -> Path:
    target = tmp_path / "yarn.lock"
    target.write_text(_BERRY_BODY, encoding="utf-8")
    return target


def test_berry_lock_picked_up_by_loader(tmp_path: Path) -> None:
    _write_berry_lock(tmp_path)
    ctx = NpmContext.from_path(tmp_path)
    assert len(ctx.locks) == 1
    lock = ctx.locks[0]
    assert lock.lockfile_version == 3
    pkgs = lock.data["packages"]
    assert "node_modules/lodash" in pkgs
    assert "node_modules/ua-parser-js" in pkgs


def test_berry_lock_npm002_clean_with_checksum(tmp_path: Path) -> None:
    _write_berry_lock(tmp_path)
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm002 = [f for f in findings if f.check_id == "NPM-002"]
    assert npm002 and all(f.passed for f in npm002)


def test_berry_lock_npm003_clean_for_registry_source(tmp_path: Path) -> None:
    _write_berry_lock(tmp_path)
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm003 = [f for f in findings if f.check_id == "NPM-003"]
    assert npm003 and all(f.passed for f in npm003)


def test_berry_lock_npm003_fires_on_git_resolution(tmp_path: Path) -> None:
    body = textwrap.dedent(
        """\
        __metadata:
          version: 6

        "forked@git:host:o/r.git":
          version: 1.0.0
          resolution: "forked@git:host:o/r.git#abc"
        """
    )
    (tmp_path / "yarn.lock").write_text(body, encoding="utf-8")
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm003 = [f for f in findings if f.check_id == "NPM-003"]
    assert npm003 and not npm003[0].passed
    assert "ssh" in npm003[0].description.lower()


def test_berry_lock_npm006_flags_compromised_version(tmp_path: Path) -> None:
    _write_berry_lock(tmp_path)  # body pins ua-parser-js@0.7.29
    ctx = NpmContext.from_path(tmp_path)
    findings = list(NpmChecks(ctx).run())
    npm006 = [f for f in findings if f.check_id == "NPM-006"]
    assert npm006 and not npm006[0].passed
    assert "ua-parser-js" in npm006[0].description


def test_berry_lock_dispatcher_routes_by_metadata_header(tmp_path: Path) -> None:
    # Same data, but a "yarn lockfile v1" comment is also present.
    # The Berry detector should still win because ``__metadata:`` is
    # the unambiguous version-2+ marker.
    body = textwrap.dedent(
        """\
        # yarn lockfile v1
        # (this comment is misleading; the body is Berry)

        __metadata:
          version: 6

        "lodash@npm:4.17.21":
          version: 4.17.21
          resolution: "lodash@npm:4.17.21"
          checksum: aaa
        """
    )
    (tmp_path / "yarn.lock").write_text(body, encoding="utf-8")
    ctx = NpmContext.from_path(tmp_path)
    pkgs = ctx.locks[0].data["packages"]
    record = pkgs["node_modules/lodash"]
    # Berry routed the checksum into the synthesized integrity field;
    # the yarn-1 parser would have left ``integrity`` empty because
    # the Berry body has no ``integrity`` line.
    assert record["integrity"].startswith("sha512-")
