"""HELM-002, ``Chart.lock`` missing or missing per-dependency digests.

A chart that declares ``dependencies:`` in ``Chart.yaml`` should ship
with a ``Chart.lock`` that records the resolved digest for each one.
Without the lock, ``helm dependency build`` is free to pull a different
version of a dependency on every fresh checkout, the same risk as
running ``npm install`` without a ``package-lock.json``. With a lock
that records versions but no ``digest:`` field, the same supply-chain
hole reappears: a compromised registry can serve a different tarball
under the same version.

The ``Chart.lock`` schema (Helm 3) carries a ``digest:`` field at
the top of the file (``sha256:...`` over the dependency tree) and
per-dependency ``digest:`` fields under ``dependencies:``. We require
the per-dependency digests because they're what ``helm dependency
build`` verifies on download.
"""
from __future__ import annotations

from typing import Any

from ...base import Finding, Location, Severity
from ...rule import Rule
from ..base import HelmContext

RULE = Rule(
    id="HELM-002",
    title="Chart.lock missing per-dependency digests",
    severity=Severity.HIGH,
    owasp=("CICD-SEC-3",),
    esf=("ESF-S-PIN-DEPS", "ESF-S-VERIFY-DEPS"),
    cwe=("CWE-494", "CWE-829"),
    recommendation=(
        "After every change to ``dependencies:`` in ``Chart.yaml``, "
        "re-run ``helm dependency update`` and commit the regenerated "
        "``Chart.lock``. The lock records the resolved version *and* a "
        "``sha256:...`` digest that ``helm dependency build`` verifies "
        "on download, without it, a compromised chart repo can swap "
        "the tarball under the same version and ``helm install`` will "
        "happily use the substitute."
    ),
    docs_note=(
        "Three failure shapes:\n\n"
        "1. ``Chart.yaml`` declares dependencies but no ``Chart.lock`` "
        "exists at all.\n"
        "2. ``Chart.lock`` exists but its ``dependencies:`` list is "
        "missing entries declared in ``Chart.yaml`` (drift after an "
        "edit without re-running ``helm dependency update``).\n"
        "3. ``Chart.lock`` lists every dependency but one or more "
        "entries lack a ``digest:`` field (lock generated by an old "
        "Helm 3 version that didn't always populate it).\n\n"
        "v1 charts (HELM-001) are skipped. They predate ``Chart.lock`` "
        "and use ``requirements.lock`` against a sibling "
        "``requirements.yaml``. Fix HELM-001 first."
    ),
    known_fp=(
        "Charts with no dependencies (the ``dependencies:`` key is "
        "absent or empty) pass automatically. There is nothing to "
        "lock.",
    ),
    exploit_example=(
        "# Vulnerable: ``Chart.yaml`` declares a redis dependency by\n"
        "# version range but ``Chart.lock`` is absent. ``helm\n"
        "# dependency build`` resolves the range against whatever the\n"
        "# chart repo serves at install time. A compromised repo (or\n"
        "# a malicious chart cache) substitutes a backdoored redis-\n"
        "# 17.x tarball; the consuming cluster runs it.\n"
        "# Chart.yaml\n"
        "apiVersion: v2\n"
        "name: my-app\n"
        "version: 1.0.0\n"
        "dependencies:\n"
        "  - name: redis\n"
        "    version: ^17.0.0\n"
        "    repository: https://charts.bitnami.com/bitnami\n"
        "# Chart.lock missing entirely — no integrity gate on\n"
        "# ``helm dependency build``\n"
        "\n"
        "# Safe: run ``helm dependency update`` and commit\n"
        "# ``Chart.lock``. ``digest:`` is the sha256 of the resolved\n"
        "# tarball; ``helm dependency build`` re-fetches and verifies\n"
        "# the digest before unpacking. A swapped tarball changes the\n"
        "# digest and the build fails loud instead of silently\n"
        "# installing the substitute.\n"
        "# Chart.lock\n"
        "dependencies:\n"
        "  - name: redis\n"
        "    repository: https://charts.bitnami.com/bitnami\n"
        "    version: 17.15.4\n"
        "    digest: sha256:abc123def456abc123def456abc123def456abc123def456abc123def456abcd\n"
        "digest: sha256:9876543210fedcba9876543210fedcba9876543210fedcba9876543210fedcba\n"
        "generated: \"2026-01-15T10:30:00Z\""
    ),
)


def check(ctx: HelmContext) -> Finding:
    offenders: list[str] = []
    locations: list[Location] = []
    for chart in ctx.charts:
        # v1 charts use requirements.yaml/.lock, handled by HELM-001.
        if chart.api_version != "v2":
            continue
        deps = chart.dependencies
        if not deps:
            continue
        dep_names: set[str] = set()
        for d in deps:
            n = d.get("name")
            if isinstance(n, str):
                dep_names.add(n)
        if chart.chart_lock is None:
            offenders.append(
                f"{chart.name}: declares {len(deps)} dependencies but "
                f"has no Chart.lock"
            )
            locations.append(Location(path=chart.chart_yaml_path))
            continue

        locked = _locked_dependencies(chart.chart_lock)
        locked_by_name: dict[str, dict[str, Any]] = {}
        for ld in locked:
            n = ld.get("name")
            if isinstance(n, str):
                locked_by_name[n] = ld

        missing_entries = sorted(dep_names - locked_by_name.keys())
        no_digest = sorted(
            name for name, entry in locked_by_name.items()
            if name in dep_names
            and not _has_sha256_digest(entry.get("digest"))
        )

        if missing_entries:
            offenders.append(
                f"{chart.name}: Chart.lock missing entries for "
                f"{', '.join(missing_entries[:3])}"
                f"{'…' if len(missing_entries) > 3 else ''}"
            )
            locations.append(
                Location(path=chart.chart_lock_path or chart.chart_yaml_path)
            )
            continue
        if no_digest:
            offenders.append(
                f"{chart.name}: Chart.lock entries without sha256 "
                f"digest: {', '.join(no_digest[:3])}"
                f"{'…' if len(no_digest) > 3 else ''}"
            )
            locations.append(
                Location(path=chart.chart_lock_path or chart.chart_yaml_path)
            )
    passed = not offenders
    desc = (
        "Every dependency-bearing chart has a ``Chart.lock`` with "
        "per-dependency sha256 digests."
        if passed else
        f"{len(offenders)} chart(s) failing the Chart.lock digest "
        f"check: {', '.join(offenders[:3])}"
        f"{'…' if len(offenders) > 3 else ''}."
    )
    return Finding(
        check_id=RULE.id, title=RULE.title, severity=RULE.severity,
        resource="helm/charts",
        description=desc,
        recommendation=RULE.recommendation, passed=passed,
        locations=locations,
    )


def _locked_dependencies(chart_lock: dict[str, Any]) -> list[dict[str, Any]]:
    deps = chart_lock.get("dependencies")
    if not isinstance(deps, list):
        return []
    return [d for d in deps if isinstance(d, dict)]


def _has_sha256_digest(value: Any) -> bool:
    """Return True if *value* looks like a populated ``sha256:...`` digest.

    Helm writes the digest as ``sha256:<64-hex>`` in ``Chart.lock``.
    We don't enforce length precisely (some tooling has emitted
    truncated forms historically) but we do require the algorithm
    prefix and a non-empty hex tail.
    """
    if not isinstance(value, str):
        return False
    s = value.strip().lower()
    if not s.startswith("sha256:"):
        return False
    tail = s.split(":", 1)[1]
    return bool(tail) and all(c in "0123456789abcdef" for c in tail)
