"""PYPI-002, requirements file missing hash pinning."""
from __future__ import annotations

from ...base import Finding, Location, Severity
from ...rule import Rule
from ..base import (
    RequirementsFile,
    has_option,
    is_editable_or_local,
    is_url_or_vcs,
    iter_specs,
)

RULE = Rule(
    id="PYPI-002",
    title="requirements.txt missing hash pinning (--require-hashes / --hash=)",
    severity=Severity.HIGH,
    owasp=("CICD-SEC-3", "CICD-SEC-9"),
    esf=("ESF-S-VERIFY-DEPS",),
    cwe=("CWE-353", "CWE-494"),
    recommendation=(
        "Regenerate the file with ``pip-compile --generate-hashes`` "
        "(pip-tools) or ``pip hash`` and add ``--require-hashes`` at "
        "the top. Every requirement line then carries one or more "
        "``--hash=sha256:...`` entries pinning the artifact bytes pip "
        "downloads. ``--require-hashes`` forces pip to refuse "
        "installs that don't match, closing the window where a "
        "compromised registry (or a malicious mirror, or a MITM on "
        "an internal proxy) swaps the tarball/wheel without your "
        "lockfile changing."
    ),
    docs_note=(
        "Fires when:\n\n"
        "* The file does not declare ``--require-hashes`` at the top, "
        "AND\n"
        "* At least one requirement line is missing a ``--hash=...`` "
        "flag.\n\n"
        "When ``--require-hashes`` is present, pip enforces hash "
        "pinning for every requirement and itself refuses the "
        "install if any line is missing a ``--hash``; the rule "
        "still flags any line that visibly lacks the flag so the "
        "doc reader sees the actual coverage. ``*.in`` (pip-tools "
        "input) files are exempt — they're declarative inputs, the "
        "compiled ``*.txt`` is the hash-bearing artifact pip "
        "installs. Complements PYPI-001 (version pin); PYPI-002 is "
        "the layer that catches an attacker swapping the artifact "
        "even when the version literal is unchanged."
    ),
    known_fp=(
        "Files generated by ``poetry export`` historically wrote "
        "hashes without ``--require-hashes`` at the top, which "
        "looks unpinned but is enforced by Poetry's own resolver "
        "in CI. Add the top-level ``--require-hashes`` to the "
        "exported file (or replace ``poetry export`` with "
        "``pip-compile --generate-hashes``) so the requirements "
        "file is self-describing.",
    ),
    incident_refs=(
        "PyTorch dependency confusion (December 2022): the "
        "``torchtriton`` name on PyPI was claimed by a malicious "
        "publisher and pulled in via a nightly build, exfiltrating "
        "SSH keys and ``/etc/passwd``. Hash pinning would have "
        "rejected the unexpected artifact regardless of which "
        "registry resolved the name.",
    ),
    exploit_example=(
        "# Vulnerable: requirements.txt pins the version literal\n"
        "# but doesn't pin the artifact bytes. A registry that\n"
        "# silently re-publishes ``requests-2.31.0`` with a\n"
        "# backdoored wheel (publisher takeover, mirror compromise,\n"
        "# MITM on an internal proxy) ships unverified code on the\n"
        "# next ``pip install``. Even ``--require-hashes`` doesn't\n"
        "# fire because the file doesn't declare it.\n"
        "# requirements.txt\n"
        "requests==2.31.0\n"
        "urllib3==2.0.7\n"
        "certifi==2024.2.2\n"
        "\n"
        "# Safe: regenerate with ``pip-compile --generate-hashes``\n"
        "# (pip-tools). Every line carries a ``--hash=sha256:...``\n"
        "# for the wheel and the sdist; ``--require-hashes`` at\n"
        "# the top makes pip refuse the install on any mismatch\n"
        "# or unhashed line.\n"
        "# requirements.txt\n"
        "--require-hashes\n"
        "requests==2.31.0 \\\n"
        "    --hash=sha256:942c5a758f98d790eaed1a29cb6eefc7ffb0d1cf7af05c3d2791656dbd6ad1e1 \\\n"
        "    --hash=sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f\n"
        "urllib3==2.0.7 \\\n"
        "    --hash=sha256:c97dfde1f7bd43a71c8d2a58e369e9b2bf692d1334ea9f9cae55add7d0dd0f84\n"
        "certifi==2024.2.2 \\\n"
        "    --hash=sha256:0569859f95fc761b18b45ef421b1290a0f65f147e92a1e5eb3e635f9a5e4e66f"
    ),
)


def check(rf: RequirementsFile) -> Finding:
    if rf.path.endswith(".in"):
        return Finding(
            check_id=RULE.id, title=RULE.title, severity=RULE.severity,
            resource=rf.path,
            description="pip-tools input file (.in); hashes live in the compiled output.",
            recommendation=RULE.recommendation, passed=True,
        )
    if rf.path.endswith("pyproject.toml"):
        return Finding(
            check_id=RULE.id, title=RULE.title, severity=RULE.severity,
            resource=rf.path,
            description=(
                "pyproject.toml is a manifest; hashes live in the "
                "resolved lockfile (poetry.lock / requirements.txt)."
            ),
            recommendation=RULE.recommendation, passed=True,
        )
    file_enforces_hashes = has_option(rf, "--require-hashes")
    offenders: list[str] = []
    locations: list[Location] = []
    for line in iter_specs(rf):
        if line.flags and any(f.startswith("--hash=") for f in line.flags):
            continue
        # An editable / local-path / URL / VCS install cannot be
        # hash-pinned, so its lack of ``--hash=`` is not a finding.
        if is_url_or_vcs(line.body) or is_editable_or_local(line.body):
            continue
        snippet = line.body if len(line.body) <= 60 else line.body[:57] + "..."
        offenders.append(f"L{line.line_no}: {snippet}")
        locations.append(Location(
            path=rf.path, start_line=line.line_no, end_line=line.line_no,
        ))
    # If the file declares ``--require-hashes`` and every line has
    # ``--hash=`` already, we pass. If ``--require-hashes`` is missing
    # but every line still carries hashes, that's pip-installable but
    # not hash-enforced; flag it as a soft fail (the registry-swap
    # window is closed line-by-line, but missing ``--require-hashes``
    # means a single unhashed addition silently downgrades the whole
    # file).
    if not offenders and file_enforces_hashes:
        passed = True
    elif not offenders:
        passed = False
        offenders.append("--require-hashes not declared at top of file")
    else:
        passed = False
    desc = (
        "Every requirement pins an artifact hash and the file "
        "declares ``--require-hashes``."
        if passed else
        f"Hash pinning incomplete: {', '.join(offenders[:5])}"
        f"{'…' if len(offenders) > 5 else ''}. A registry that "
        f"swaps the artifact bytes ships unverified code on the "
        f"next install."
    )
    return Finding(
        check_id=RULE.id, title=RULE.title, severity=RULE.severity,
        resource=rf.path, description=desc,
        recommendation=RULE.recommendation, passed=passed,
        locations=locations,
    )
