"""Starter ``.pipeline-check.yml`` template used by ``pipeline_check init``.

Keep the keys in sync with ``pipeline_check.core.config._TOPLEVEL_KEYS``
and ``_GATE_KEYS``, every key shown here is also a legal config-file
key. Values are commented out so the generated file is a no-op until
the user edits it.

When ``init`` runs a scan first (the default), :func:`render_smart` is
used instead of :func:`render` and pre-fills the gate block with a
recommended ``fail_on`` plus a baseline-file pointer derived from the
current scan. The goal is that a brand-new user's first
``pipeline_check`` run after ``init`` returns exit 0, every legacy
finding is baselined, and new regressions are what fails CI.
"""
from __future__ import annotations

from .checks.base import Severity


def render(detected_pipeline: str | None = None) -> str:
    """Return the YAML scaffold, pre-filling ``pipeline:`` when known."""
    pipeline_line = (
        f"pipeline: {detected_pipeline}"
        if detected_pipeline
        else (
            "# pipeline: github    # aws | github | gitlab | bitbucket | azure"
            " | jenkins | circleci | cloudbuild | cloudformation | terraform"
            " | dockerfile | kubernetes"
        )
    )
    return f"""# .pipeline-check.yml, configuration for pipeline_check
# Keys mirror CLI flags (hyphens -> underscores). Env vars
# PIPELINE_CHECK_* override this file; CLI flags override both.
# Run `pipeline_check --config-check` to validate after editing.

{pipeline_line}

# ── Filtering ──────────────────────────────────────────────────────────────
# checks:                    # run only these check IDs
#   - GHA-001
#   - CB-003
# severity_threshold: INFO   # CRITICAL | HIGH | MEDIUM | LOW | INFO
# secret_patterns:           # extra regexes for secret scanning
#   - "^sk_live_[A-Za-z0-9]{{24,}}$"

# ── Output ─────────────────────────────────────────────────────────────────
# output: terminal           # terminal | json | html | sarif | junit | markdown | both
# output_file: report.json
# standards:                 # annotate findings with these standards
#   - owasp_cicd_top_10

# ── Provider path hints (only used by their matching pipeline) ────────────
# tf_plan: plan.json
# gha_path: .github/workflows
# gitlab_path: .gitlab-ci.yml
# bitbucket_path: bitbucket-pipelines.yml
# azure_path: azure-pipelines.yml
# circleci_path: .circleci/config.yml
# cloudbuild_path: cloudbuild.yaml
# dockerfile_path: Dockerfile
# k8s_path: kubernetes/

# ── CI gate ────────────────────────────────────────────────────────────────
gate:
  # fail_on: HIGH             # fail if any finding is >= this severity
  # min_grade: B              # fail if overall grade is worse than this
  # max_failures: 5           # fail when more than N findings fail
  # fail_on_checks:           # always fail when these check IDs fail
  #   - IAM-001
  # baseline: baseline.json
  # ignore_file: .pipelinecheckignore
"""


def recommend_fail_on(grade: str, has_critical: bool) -> Severity:
    """Pick a ``fail_on`` threshold for the generated config.

    The smart-init flow wants the first CI run after ``init`` to be a
    realistic-but-not-overwhelming gate, baselining current debt and
    failing on new regressions. The rule of thumb:

    - Any CRITICAL failure → gate on HIGH (so new highs also block
      while CRITICALs are baselined).
    - Grade A or B → MEDIUM (the bar is already there, hold the line).
    - Grade C / D and no CRITICAL → HIGH (most common case for a
      first-ever scan on a legacy repo).
    """
    if has_critical:
        return Severity.HIGH
    if grade in ("A", "B"):
        return Severity.MEDIUM
    return Severity.HIGH


def render_smart(
    detected_pipeline: str | None,
    *,
    fail_on: Severity,
    baseline_path: str,
    write_baseline: bool,
) -> str:
    """Render a config scaffold with the gate pre-filled from a scan.

    ``write_baseline`` controls whether the gate references the
    baseline file. False when the scan had no failing findings (no
    need to baseline anything), True otherwise. The pipeline key is
    uncommented when ``detected_pipeline`` is set, mirroring
    :func:`render`.
    """
    pipeline_line = (
        f"pipeline: {detected_pipeline}"
        if detected_pipeline
        else (
            "# pipeline: github    # aws | github | gitlab | bitbucket | azure"
            " | jenkins | circleci | cloudbuild | cloudformation | terraform"
            " | dockerfile | kubernetes"
        )
    )
    baseline_block = (
        f"  baseline: {baseline_path}\n"
        if write_baseline
        else f"  # baseline: {baseline_path}    # no failing findings to baseline yet\n"
    )
    return f"""# .pipeline-check.yml, configuration for pipeline_check
# Generated by `pipeline_check init`, edit freely.
# Keys mirror CLI flags (hyphens -> underscores). Env vars
# PIPELINE_CHECK_* override this file; CLI flags override both.
# Run `pipeline_check --config-check` to validate after editing.

{pipeline_line}

# ── Filtering ──────────────────────────────────────────────────────────────
# checks:                    # run only these check IDs
#   - GHA-001
# severity_threshold: INFO   # CRITICAL | HIGH | MEDIUM | LOW | INFO

# ── Output ─────────────────────────────────────────────────────────────────
# output: terminal           # terminal | json | html | sarif | junit | markdown | both
# standards:                 # annotate findings with these standards
#   - owasp_cicd_top_10

# ── CI gate ────────────────────────────────────────────────────────────────
# Tuned by `pipeline_check init` against the current scan. The baseline
# file captures existing failures so this gate only blocks on *new*
# regressions; delete the baseline line to gate on every failure.
gate:
  fail_on: {fail_on.value}
{baseline_block}  # min_grade: B
  # max_failures: 5
  # fail_on_checks:
  #   - IAM-001
  # ignore_file: .pipelinecheckignore
"""
